### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#1]
I think the code really needs to be refactored. It's _particularly important_ to implement getters for our database `struct`s as the naming of their fields is highly inconsistent. I've no idea of how long this could take but we should definitely consider it when there's no high priority task.

It may certainly be useful to agree upon some naming and style convention and write a wiki page about it. What did we decide to do about the [_Google style guidelines_](https://google.github.io/styleguide/cppguide.html)?

**Comment by deknapp** [comment]
I am rewriting my part of the code from scratch, and happy to use the
Google style guidelines while I write it.

It would also be nice to have a wiki specific to the code that I can add to
/ refer to as I'm writing my part.

Nathaniel

On Wed, Jun 15, 2016 at 7:05 PM, pdigiglio notifications@github.com wrote:

> I think the code really needs to be refactored. It's _particularly
> important_ to implement getters for our database structs as the naming of
> their fields is highly inconsistent. I've no idea of how long this could
> take but we should definitely consider it when there's no high priority
> task.
> 
> It may certainly be useful to agree upon some naming and style convention
> and write a wiki page about it. What did we decide to do about the _Google
> style guidelines_ https://google.github.io/styleguide/cppguide.html?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwHov5p4AE_D_Ezh2QgEdSrd_jjDvks5qMDDPgaJpZM4I2lOL
> .

## 

Nathaniel

**Comment by wilhelma** [comment]
I’m a big fan of refactoring (I think it belongs to successful software engineering).
However, let us have a meeting before where we clarify all the attributes and their naming.

Best

**Comment by pdigiglio** [comment]
Besides naming and coding conventions, I think it could be a nice idea to reorganize the file structure. My idea is, for example, something like:

``` sh
$PROJECT_ROOT/
├── include
│   ├── events
│   ├── rapidjson
│   ├── tables
│   └── tools
└── src
    └── tools
```

The header _Event.h_ would be split in as many headers as events it contains which would then be placed in `include/events`. Same for _DBDataModel.h_, whose daughters would go in `include/tables`.

Please, let me know what you think.

**Comment by deknapp** [comment]
This is fine with me

On Thu, Jun 16, 2016 at 3:51 PM, pdigiglio notifications@github.com wrote:

> Besides naming and coding conventions, I think it could be a nice idea to
> reorganize the file structure. My idea is, for example, something like:
> 
> $PROJECT_ROOT/
> ├── include
> │   ├── events
> │   ├── rapidjson
> │   ├── tables
> │   └── tools
> └── src
>     └── tools
> 
> The header _Event.h_ would be split in as many headers as events it
> contains which would then be placed in include/events. Same for
> _DBDataModel.h_, whose daughters would go in include/tables.
> 
> Please, let me know what you think.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/1#issuecomment-226490784,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwMJXvaOb_eU-Wso2WNNW51ivHSQbks5qMVTGgaJpZM4I2lOL
> .

## 

Nathaniel
