### ISSUE TITLE
Branches usage

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#13]
I've seen the _development_ branch has diverted pretty much from mine; I'm a little confused. I propose that:
1. We keep a branch with the simulator only, i.e. what used to be in _development_, as I don't need @deknapp's code;
2. We don't commit and push non-compiling code.

If there are no objections, I'll merge the changes to the simulator in my fork and I'll make a new branch here.

@deknapp I thought it was a good idea to change the `Tool` methods. They should be much more meaningful now.

**Comment by deknapp** [comment]
Can someone please check the previous issue I posted? I can't proceed until
I figure this out and it's not from my code

**Comment by deknapp** [comment]
The development branch still compiles, and was forked from the most recent
changes you posted. I haven't seen any of the changes you have done Paolo
because as if this morning you hadn't committed for four days.

Also although you don't need my code, I certainly need yours, and it's
useless if I'm trying to develop off of a branch that uses your old code.

Can you please commit your Tool changes to the development branch? I will
only push compiling.good versions to that branch. My own nath-devel branch
may have intermediate commits that don't compile but that shouldn't affect
you.

On Tuesday, July 12, 2016, pdigiglio notifications@github.com wrote:

> I've seen the _development_ branch has diverted pretty much from mine;
> I'm a little confused. I propose that:
> 1. We keep a branch with the simulator only, i.e. what used to be in
>    _development_, as I don't need @deknapp https://github.com/deknapp's
>    code;
> 2. We don't commit and push non-compiling code.
> 
> If there are no objections, I'll merge the changes to the simulator in my
> fork and I'll make a new branch here.
> 
> @deknapp https://github.com/deknapp I thought it was a good idea to
> change the Tool methods. They should be much more meaningful now.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/13, or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwJ52lPjem3ezIRQjIXVaMlh8i8ajks5qU26mgaJpZM4JKQr-
> .

## 

Nathaniel

**Comment by wilhelma** [comment]
@pdigiglio I agree to Nathaniel, the development branch can include tools if they are compilable.
What I didn't get is the problem you're facing currently. Can you elaborate on this (or come by at my office)?

**Comment by pdigiglio** [comment]
I was not saying that we should reserve _development_ for the simulator only; I was just proposing that we keep a separate branch for it. Also, I think we should not track the database files.

**Comment by deknapp** [comment]
Sorry, the database files were my fault - I'll change the .gitignore back
so that they are ignored.

On Tue, Jul 12, 2016 at 2:48 PM, pdigiglio notifications@github.com wrote:

> I was not saying that we should reserve _development_ for the simulator
> only; I was just proposing that we keep a separate branch for it. Also, I
> think we should not track the database files.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/13#issuecomment-232036779,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwD-_R0oiGnKrXNn62lwx2TzBz8ORks5qU40RgaJpZM4JKQr-
> .

## 

Nathaniel

**Comment by deknapp** [comment]
Bare with me, I'm still fairly new to github, but where are your most recent changes @pdigiglio? I can't find the tool changes anywhere. If I go to your fork there are no recent changes.

**Comment by pdigiglio** [comment]
To keep track of what's going on I look at [_Graphs > Network_](https://github.com/wilhelma/pcvInterpreter/network). There you have a pretty useful overview of the branches histories (also of forked repository). As of now, my latest pushed commit is [this](https://github.com/pdigiglio/pcvInterpreter/commit/34774808f053f10f8ae6fd8d6d74e71597043341) from my _development_ branch.

If I don't commit it's usually because I'm trying to solve a problem and I don't want to save code that doesn't work. Also, the time I can devote to this project is not much.

At the moment, besides investigating on #14, I'm still looking for a clever way to integrate the changes that have been made in my fork. Then I will make a _simulator_ branch here, which only contains the simulator code.

**Comment by pdigiglio** [comment]
I made a _simulator_upstream_ branch (I wasn't able to call it differently). I'll push code that doesn't crash on my machine and I'll try to use it in such a way that the commit history is meaningful and descriptive.

@deknapp I changed `Tool`'s interfaces. Please let me know if the update makes sense to you.

**Comment by deknapp** [comment]
@pdigiglio  I am merging all these changes now into my branch. I am keeping the TIME last_acquire_time member of ShadowLock object. I need to keep track of this for my tool. 

In the future, can you push more frequently? It makes it much easier to merge your changes, and helps me avoid developing using interfaces from your old code.

**Comment by deknapp** [comment]
To clarify, I mean, can you push your changes to a branch that I can see on the main fork?
