### ISSUE TITLE
Funny String Error in ShadowVar

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#14]
I get a `std::bad_alloc` exception when I run the simulator on _nested_test_with_calls.db_. The error occurs during the allocation of `ShadowVar::name` in `DBInterpreter::processMemAccess()`. @wilhelma and I already tried to investigate my code and its behavior on my machine without getting very far.

I found out the input constructor parameter `Name` itself is corrupted in `ShadowVar`: its length is 17179869187 B = 16 GiB. I'll still investigate on the code but it may be that the database itself is corrupted (even though I don't think so). @deknapp could you provide me with the three source codes you used to produce the databases?

Interestingly, this doesn't happen if I print on the screen any of `reference`'s members in `DBInterpreter::processMemAccess()` before allocating the `ShadowVar`.

**Comment by deknapp** [comment]
I don't think the database nested_test_with_calls.db is working @pdigiglio. It didn't do anything when I tried to use it, and also, since then @wilhelma  fixed bugs in the database generator. So if your code works with the busy_test.db, I would ignore nested_test_with_calls.db

**Comment by pdigiglio** [comment]
Some magic seems to have occurred in [925222e](https://github.com/wilhelma/pcvInterpreter/commit/925222e78df5bc5e2113d7abd8498ecb2c3b08f4) and the bug disappeared.
