### ISSUE TITLE
test_codes directory

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#15]
Should we make a directory for the C/C++ codes we use to test the simulator?

**Comment by deknapp** [comment]
Yes. I will add one to the development branch.

On Wed, Jul 13, 2016 at 9:07 AM, pdigiglio notifications@github.com wrote:

> Should we make a directory for the C/C++ codes we use to test the
> simulator?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/15, or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwD3Hm4CYYxPNFT7mLRdJV4zeaEXlks5qVI62gaJpZM4JLH5F
> .

## 

Nathaniel

**Comment by deknapp** [comment]
It's added.
