### ISSUE TITLE
Possible bug in timeStringToTime(TIME_STRING timeString) function

### ISSUE THREAD

**Issue by deknapp** [wilhelma/pcvInterpreter#17]
@pdigiglio @wilhelma 
I'm getting a very high number for the start time in the new thread event. I think that the function timeStringToTime might be miscalculating (lines 55 to 61 of Event.h). Can someone check this?

**Comment by pdigiglio** [comment]
You could check the number against its actual value in a database or you can tell me how to reproduce the (possible) bug and I'll try.

**Comment by deknapp** [comment]
There is no "bug" to reproduce. It's just the function, whose location I
just gave, that I don't think is producing the correct time.

On Wed, Jul 13, 2016 at 1:36 PM, pdigiglio notifications@github.com wrote:

> You could check the number against its actual value in a database or you
> can tell me how to reproduce the (possible) bug and I'll try.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/17#issuecomment-232329981,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwH-7PCzePl151VK0ilfVFMW_vjPQks5qVM2vgaJpZM4JLSPy
> .

## 

Nathaniel

**Comment by pdigiglio** [comment]
I perfectly understand that you're not saying there is a bug. I'm telling that either you can check yourself if the time is correct by looking at its actual value in the database or you have to make a more circumstantial request for help by specifying at least the following:
1. What is "a very high number", e.g. compared to what expectation, or any other explanation for why you think it's too high;
2. Which database I should interpret to get such a number.

We're all pretty busy and I think none of us will start looking for an error if he doesn't even know what to look for. Or, at least, I can surely tell you that I won't so let's please try to meet each other halfway.

**Comment by deknapp** [comment]
OK, never mind. I understand.

On Wed, Jul 13, 2016 at 4:42 PM, pdigiglio notifications@github.com wrote:

> I perfectly understand that you're not saying there is a bug. I'm telling
> that either you can check yourself if the time is correct by looking at its
> actual value in the database or you have to make a more circumstantial
> request for help by specifying at least the following:
> 1. What is "a very high number", e.g. compared to what expectation, or
>    any other explanation for why you think it's too high;
> 2. Which database I should interpret to get such a number.
> 
> We're all pretty busy and I think none of us will start looking for an
> error if he doesn't even know what to look for. Or, at least, I can surely
> tell you that I won't so let's please try to meet each other halfway.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/17#issuecomment-232376951,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwDKqmVj5CInYxyjQsmDbX-KpxcM3ks5qVPlHgaJpZM4JLSPy
> .

## 

Nathaniel

**Comment by deknapp** [comment]
I'm closing the issue because I can't find anything wrong with the function.

**Comment by deknapp** [comment]
@pdigiglio I found that the function only converts the second component of the time stamp, so it is incorrect.

**Comment by deknapp** [comment]
converting string 2016-07-12T17:16:50.427174341Z 
result is 427 

inline
const TIME timeStringToTime(const TIME_STRING& t) {
    printf("converting string %s \n", t.c_str());
	int found = t.find_last_of('.');
    TIME result = static_cast<TIME>(atoi(t.substr(found + 1).c_str()));
    printf("result is %lu \n", result/CLOCKS_PER_SEC);
	return static_cast<TIME>(atoi(t.substr(found + 1).c_str()));
}

**Comment by deknapp** [comment]
@pdigiglio sorry for the trouble, but what does `YYYY-MM-DD|T|hh:mm:ss|.|CLOCK|Z| mean? Is the |CLOCK|Z| part a separate format for the time in the left half, or is it an expression for the time?

**Comment by pdigiglio** [comment]
I actually don't know that. I think it's the CPU clock. @wilhelma may explain us.

**Comment by wilhelma** [comment]
That is the wall clock time string including nanoseconds. All other timestamps in the application are clock cycles. By this approach it's possible to relate all timestamps across threads (even with unsynchronized cpu cores).

```
static inline std::string getTimeString()
{
    char timeString[100];
    char timeStringWithNanoseconds[200];
    struct tm t;
    struct timespec ts;

    clock_gettime(CLOCK_REALTIME, &ts);
    gmtime_r(&(ts.tv_sec), &t);

    strftime(timeString, sizeof(timeString), "%FT%T", &t);
    snprintf(timeStringWithNanoseconds, sizeof(timeStringWithNanoseconds),
             "%s.%ldZ", timeString, ts.tv_nsec);

    return std::string(timeStringWithNanoseconds);
}
```

**Comment by pdigiglio** [comment]
Just a confirmation: what I had in mind when writing `timeStringToTime()` was to extract the number between the point and the "Z" from the string and return it. Besides the bug, is that correct?

**Comment by deknapp** [comment]
I don't think there's a bug, the code does exactly that. I just got
confused because I thought the number between the point and the Z was part
of the other part of the time, but it's just wall time.

On Wed, Jul 13, 2016 at 10:06 PM, pdigiglio notifications@github.com
wrote:

> Just a confirmation: what I had in mind when writing timeStringToTime()
> was to extract the number between the point and the "Z" from the string and
> return it. Besides the bug, is that correct?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/17#issuecomment-232470824,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwOeDnbNJEHNxJqObGszz9wBN2oB7ks5qVUU0gaJpZM4JLSPy
> .

## 

Nathaniel
