### ISSUE TITLE
EventService::publish()

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#2]
@wilhelma I need a clarification. In the file [_EventService.cpp_](https://github.com/wilhelma/pcvInterpreter/blob/development/src/EventService.cpp) I believe that the bitwise operator `|` should be replaced by `&`, e.g.

``` cpp
bool EventService::publish(NewThreadEvent *event) {
    _observers_t::iterator it;
    for (it = _observers.begin(); it != _observers.end(); ++it)
    if ( (it->second.events | Events::NEWTHREAD) != 0 ) // always != 0
            it->first->create(event);

    return true;
}
```

should indeed be

``` cpp
bool EventService::publish(NewThreadEvent *event) {
    _observers_t::iterator it;
    for (it = _observers.begin(); it != _observers.end(); ++it)
    if ( (it->second.events & Events::NEWTHREAD) != 0 )
            it->first->create(event);

    return true;
}
```

Is that correct or don't I get the purpose of such methods?

**Comment by wilhelma** [comment]
True! But look into the implementation of the operator, maybe we need to change the definition and other uses.
