### ISSUE TITLE
Use exceptions instead of return values.

### ISSUE THREAD

**Issue by wilhelma** [wilhelma/pcvInterpreter#20]
Currently, integer return types are used for most functions.
I would highly suggest to refactor the code so that meaningful exceptions are used to improve readability and maintainability.

**Comment by pdigiglio** [comment]
That was also an idea of mine but so far I know too few about exceptions to embrace such a task. If it's not a priority, I'd like to do it.

**Comment by wilhelma** [comment]
@pdigiglio It's your turn.

**Comment by pdigiglio** [comment]
Run-time errors are not identified by checking the return values of the functions anymore.
