### ISSUE TITLE
Time stamps are not sequential 

### ISSUE THREAD

**Issue by deknapp** [wilhelma/pcvInterpreter#23]
@wilhelma 
I get a bug with time stamps if I run the code from my most recent commit (7cecc40) on one of the databases you just sent me. 
./pcv busy_test_2_threads.db
The problem is that the time stamp for the new thread that calls the second instance of _Z8BusyWorkPv is not greater than the time stamp of the last return (the return of the first call of _Z8BusyWorkPv). If you run the code, you can see where the assertion fails exactly - line 156 of ParasiteTool.cpp. 

I assume the time stamps for sequential events should also be sequential - is this correct? Or do the time stamps reflect the times from concurrent execution of the two threads?

**Comment by wilhelma** [comment]
Fixed in 898d10b
