### ISSUE TITLE
Get rid of Interpreter and only keep DBInterpreter

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#24]
Is it necessary to have `DBInterpreter` derive from `Interpreter`?  Can I move `Interpreter`'s functionality (i.e. the logger initialization) in `DBInterpreter` and remove it?

**Comment by wilhelma** [comment]
The Interpreter class is an additional indirection that is not necessary at the moment.
I absolutely favor to remove the Interpreter.
