### ISSUE TITLE
Missing operator+ for TIME variables

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#28]
Implement an `operator+()` for `TIME` variables.

@deknapp Do you only need it for `TIME`?

**Comment by deknapp** [comment]
Yes, just for TIME. An operator-() would also be nice but of course I can just use the operator+() for that.

**Comment by pdigiglio** [comment]
Done in [bfe951d](https://github.com/wilhelma/pcvInterpreter/commit/bfe951d9c708524c27340665fcabfaf5b55259b3). Please close the issue if it works.
