### ISSUE TITLE
Thread End Event

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#3]
@deknapp Do you also want a thread ID in the `ThreadEndEvent`?

@wilhelma The `Thread::EndTime` field in the database is the join time, which is not what we want, right?

**Comment by deknapp** [comment]
I don't necessarily need a thread ID in the ThreadEndEvent but if it's
easily to implement that would be nice.

On Thu, Jun 30, 2016 at 3:59 PM, pdigiglio notifications@github.com wrote:

> @deknapp https://github.com/deknapp Do you also want a thread ID in the
> ThreadEndEvent?
> 
> @wilhelma https://github.com/wilhelma The Thread::EndTime field in the
> database is the join time, which is not what we want, right?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/3, or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwMIuOeZ2bcqH7WaBTlNFPYlO9TTIks5qQ8urgaJpZM4JCMDw
> .

## 

Nathaniel

**Comment by pdigiglio** [comment]
It was actually pretty easy so the thread ID is also available in the event. The `ThreadEndEvent` is thrown when a fork happens, so basically right after a `NewThreadEvent`. Is it a problem for your algorithm?

**Comment by deknapp** [comment]
No, it shouldn't be.
