### ISSUE TITLE
Problems with binary expressions in EventService.cpp

### ISSUE THREAD

**Issue by deknapp** [wilhelma/pcvInterpreter#4]
I'm getting these error messages in the development branch: 
error: invalid operands to binary expression ('enum Events' and 'Events'), for lines 17, 37, 46, etc. 

@pdigiglio I'm going to fix these errors today because I need the code to compile in order to test my code . If my fixes look acceptable you can merge with my branch "nathan-debug," otherwise I will take your corrections next time I merge with the development branch.

**Comment by deknapp** [comment]
It was a simple fix, just casting both binary operands as (int)

**Comment by pdigiglio** [comment]
Can you please tell me where? I always check if the code compiles before committing it. I just tried on my home computer and I don't get any error.

Anyway, pay attention as I'm migrating from `enum`'s to `class enum`'s and this may cause namespace problems.

**Comment by pdigiglio** [comment]
Sorry, I didn't read the title. I'll wait to see your fix and I'll compare it to my code!

**Comment by deknapp** [comment]
In the binary operands for lines 17, 37, 46, etc. (third line of each publish event) in the file EventService.cpp.

**Comment by deknapp** [comment]
It may be a compiler difference on my mac. I'm fixing merge conflicts with my code at the moment so I certainly wouldn't combine the developer branch with it.

**Comment by deknapp** [comment]
@pdigiglio I also added the THREADENDEVENT in the enum in Event.h - it was missing. I wasn't sure which hex value to use so I chose 0x80

**Comment by pdigiglio** [comment]
I just pushed two commits. The second one may solve your problem.

My `enum` looks like this, `THREADEND` is the second entry:

``` cpp
enum class Events: unsigned char {
    NEWTHREAD = 0x1,  // 00000001
    THREADEND = 0x2,  // 00000010
    JOIN      = 0x4,  // 00000100
    ACQUIRE   = 0x8,  // 00001000
    RELEASE   = 0x10, // 00010000
    ACCESS    = 0x20, // 00100000
    CALL      = 0x40, // 01000000
    RETURN    = 0x80, // 10000000
    ALL       = 0xFF  // 11111111
};
```

Moreover, there should be no need for the cast to use `operator&` as it's defined (also in _Event.h_):

``` cpp
constexpr inline
Events operator& (Events A, Events B) noexcept {
    return static_cast<Events>(
        static_cast<std::underlying_type<Events>::type>(A) &
        static_cast<std::underlying_type<Events>::type>(B)   );
}
```

This should do the job for you ;)

Please let me know if the problem is solved!

**Comment by deknapp** [comment]
I committed your most recent changes, and I still get the same errors for these operands. I don't see any harm in adding the (int) cast for these expressions - is this OK with you @pdigiglio ?

**Comment by pdigiglio** [comment]
For me it's fine but it's a hack. We can keep it as far as we don't find a better solution, i.e. we've to find out what part of the code is not portable and fix it. I mean, the point of defining operators is that you shouldn't have to cast.

**Comment by pdigiglio** [comment]
If you still have to cast, the issue is not closed. Was the problem fixed?

**Comment by deknapp** [comment]
OK, sorry I will reopen it.

On Mon, Jul 11, 2016 at 4:08 PM, pdigiglio notifications@github.com wrote:

> If you still have to cast, the issue is not closed. Was the problem fixed?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/4#issuecomment-231744930,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwEz_v4qPw7-7ZCCEU3EBI0OIzNoPks5qUk5JgaJpZM4JD21x
> .

## 

Nathaniel

**Comment by deknapp** [comment]
This has been fixed already by you I believe @pdigiglio, I don't see any casting in EventService.cpp anymore.
