### ISSUE TITLE
Seg fault within processInstruction(...)

### ISSUE THREAD

**Issue by deknapp** [wilhelma/pcvInterpreter#5]
Hi @wilhelma and @pdigiglio, 
I tried running one of the database tests (made from the C program below), and it throws a segmentation fault within the processInstruction function  (lines 183-257 of DBInterpreter.cpp), called from line 114 of DBInterpreter::process(), called from runner->interpret() in the main function. I commented out my Parasite code, so the source of the problem should be something in the main code base. Maybe it's something to do with the calls in scale_test.c to pthread_create(...), but our code should be able to support pthread calls. I'm looking for the bug already but I thought I should let you know. 
# include <pthread.h>
# include <stdio.h>
# include <stdlib.h>
# include <unistd.h>
# define NUM_THREADS 2

void *PrintHello(void *threadid)
{
   long tid;
   tid = (long)threadid;
   printf("Hello World! It's me, thread #%ld!\n", tid);
   usleep(2000);
   pthread_exit(NULL);
}

int main(int argc, char *argv[])
{
   pthread_t threads[NUM_THREADS];
   int rc;
   long t;
   for(t=0;t<NUM_THREADS;t++){
     printf("In main: creating thread %ld\n", t);
     rc = pthread_create(&threads[t], NULL, PrintHello, (void *)t);
     if (rc){
       printf("ERROR; return code from pthread_create() is %d\n", rc);
       exit(-1);
       }
     }

   /\* Last thing that main() should do */
   pthread_exit(NULL);
}

**Comment by deknapp** [comment]
I now know via debugging that the seg fault happens when an ALLOC instruction is being processed. Lines 207-211 of DBInterpreter.cpp

**Comment by deknapp** [comment]
@wilhelma @pdigiglio it's a seg fault with the following statement
 search_call = callTable.find(search_segment->second.call_id);
This is on about line 205 of DBInterpreter.cpp (line count is off because I inserted some print statements).

**Comment by deknapp** [comment]
No, it's actually not there, sorry. It's further into the function. @wilhelma @pdigiglio

**Comment by deknapp** [comment]
It's this line in DBInterpreter.cpp (about line 245): for (const auto& it : accessTable.getInsAccessMap().find(ins.instruction_id)->second)

**Comment by wilhelma** [comment]
Fixed it... The bug was caused due to a unsafe usage of chained iterator accesses.

see submit
