### ISSUE TITLE
Seg fault 

### ISSUE THREAD

**Issue by deknapp** [wilhelma/pcvInterpreter#6]
@pdigiglio @wilhelma I still get a segmentation fault when I run any of the test cases using the development branch, without any of my changes. This could be something with my mac compiler, but you could you double check that it runs on your computers, so I know to focus on issues that would be caused by the compiler?

**Comment by deknapp** [comment]
@pdigiglio @wilhelma I'm guessing it's the same statement that I mentioned in the previous post. I can't test anything until this is resolved...

**Comment by deknapp** [comment]
this is the debug message I get using lldb: \* 
thread #1: tid = 0x2596a, 0x0000000100013826 SAAPFramework`ACC_ID::operator<(ACC_ID const&) const + 22, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x12)
    frame #0: 0x0000000100013826 SAAPFramework`ACC_ID::operator<(ACC_ID const&) const + 22
SAAPFramework`ACC_ID::operator<:
->  0x100013826 <+22>: cmpl   (%rsi), %eax
    0x100013828 <+24>: setb   %cl
    0x10001382b <+27>: andb   $0x1, %cl
    0x10001382e <+30>: movzbl %cl, %eax

**Comment by pdigiglio** [comment]
I don't get any segmentation fault on either of the test databases. I'd recommend you try to compile the code with _GCC_ and see what happens. If it works, maybe some parts of my code are not portable. Please let me know if you can do that.

**Comment by deknapp** [comment]
@pdigiglio  I'm not able to compile with GCC on my mac. I've tried for hours before to change the compiler, and it just won't let me change it from clang. It would be great if we could somehow figure out why there is a seg fault on the mac - maybe it indicates an underlying problem in the code. Running a virtual machine is slow and a big pain. I think it's throwing the seg fault on the line:
auto searchAccess = accessTable.find(it); 
This is in the processInstruction() function at about line 240 in DBInterpreter. There may be something wrong with this function because the code keeps throwing seg faults here.

**Comment by deknapp** [comment]
@pdigiglio @wilhelma Which compiler exactly are you using for your code?

**Comment by wilhelma** [comment]
I’m using gcc 4.9. Have you thought about a vm?

**Comment by pdigiglio** [comment]
I'm using _GCC_:

```
 % gcc --version
gcc (GCC) 6.1.1 20160602
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by deknapp** [comment]
@wilhelma @pdigiglio  Using a VM is incredibly slow for me. But I guess I have no other option if I can't figure out this seg fault.

**Comment by deknapp** [comment]
@wilhelma @pdigiglio Doesn't it indicate a problem with the code that should be fixed, if it throws a seg fault with Clang?

**Comment by deknapp** [comment]
@wilhelma @pdigiglio I know the bug is in processInstruction(...) in DBInterpreter.cpp, at about line 240.

**Comment by wilhelma** [comment]
The debug output looks like it’s a bug in the boost typedefs… How did you install boost?

**Comment by deknapp** [comment]
I installed boost using homebrew. I didn't understand the debug output, it
had something to do with the < operator on ACC_ID.

On Mon, Jul 4, 2016 at 9:45 PM, wilhelma notifications@github.com wrote:

> The debug output looks like it’s a bug in the boost typedefs… How did you
> install boost?
> 
> > On 04 Jul 2016, at 21:42, deknapp notifications@github.com wrote:
> > 
> > @wilhelma https://github.com/wilhelma @pdigiglio <
> > https://github.com/pdigiglio> I know the bug is in
> > processInstruction(...) in DBInterpreter.cpp, at about line 240.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub <
> > https://github.com/wilhelma/pcvInterpreter/issues/6#issuecomment-230346454>,
> > or mute the thread <
> > https://github.com/notifications/unsubscribe/AEDDw1z_XoVjgynXkIprup3WfF9hfaPjks5qSWI8gaJpZM4JEUm2
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/6#issuecomment-230346674,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwJgYjupQ5--WHLLy_pV_tRk4OwLfks5qSWLMgaJpZM4JEUm2
> .

## 

Nathaniel

**Comment by wilhelma** [comment]
which is a boost strong typedef… if that’s the whole call-stack, I assume it’s a boost problem.

**Comment by pdigiglio** [comment]
By the way, one of my plans for the future was to write _boost_-free code and to use only standard C++ libraries.

@deknapp Anyway I don't recommend you to wait for that as it will certainly take a very long time.

**Comment by deknapp** [comment]
Which version of boost are you using?

On Mon, Jul 4, 2016 at 10:00 PM, pdigiglio notifications@github.com wrote:

> By the way, one of my plans for the future was to write _boost_-free code
> and to use only standard C++ libraries.
> 
> @deknapp https://github.com/deknapp Anyway I don't recommend you to
> wait for that as it will certainly a take very long time.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/6#issuecomment-230348028,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwG4T85ubx3w9vmM6nwa9Ih56BlvZks5qSWZNgaJpZM4JEUm2
> .

## 

Nathaniel

**Comment by deknapp** [comment]
I am using

boost-1.57.0

On Mon, Jul 4, 2016 at 10:01 PM, Nathaniel Knapp nathaniel.knapp@gmail.com
wrote:

> Which version of boost are you using?
> 
> On Mon, Jul 4, 2016 at 10:00 PM, pdigiglio notifications@github.com
> wrote:
> 
> > By the way, one of my plans for the future was to write _boost_-free
> > code and to use only standard C++ libraries.
> > 
> > @deknapp https://github.com/deknapp Anyway I don't recommend you to
> > wait for that as it will certainly a take very long time.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/wilhelma/pcvInterpreter/issues/6#issuecomment-230348028,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AHqFwG4T85ubx3w9vmM6nwa9Ih56BlvZks5qSWZNgaJpZM4JEUm2
> > .
> 
> ## 
> 
> Nathaniel

## 

Nathaniel

**Comment by pdigiglio** [comment]
I'm using version 1.60.0-5.

**Comment by wilhelma** [comment]
1.60

**Comment by pdigiglio** [comment]
`BOOST_STRONG_TYPEDEF` is not strictly necessary but the standard C++ `typedef` is not type-safe:

``` cpp
typedef float mass;
typedef float distance;

bool lessThan(mass a, mass b) {
    return a < b;
}

int main() {
    mass     m = 10.;
    distance d = 9.;

    // This will compile as the underlying types of mass and
    // distance are the same but it's logically wrong
    lessThan(d, m);

    return 0;
}
```

I just use it to prevent logical errors like the one shown in the snippet above.

@deknapp You can also replace them with ordinary `typedef`'s if it solves your problem.

**Comment by pdigiglio** [comment]
For the sake of completeness, I just compiled the code with _clang_ on _Arch Linux_:

```
% clang --version
clang version 3.8.0 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
% cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
```

I don't get any segmentation fault.

**Comment by deknapp** [comment]
OK. Could I argue that the code is still incomplete, if it doesn't work on my Mac?
Or am I doomed to using a extremely slow virtual machine on my Mac for the rest of the summer?

**Comment by pdigiglio** [comment]
I think it's a fair statement. As I already wrote, all I can do to help you is getting rid of the `BOOST_STRONG_TYPEDEF`'s. However I can't tell you now how long this will take because I don't know how much code will need to be fixed. Hopefully not much; I'll let you know as soon as I have an estimate.

**Comment by wilhelma** [comment]
To speed things up… I’ll try the stuff on my mac :)

**Comment by deknapp** [comment]
I now have the most current version of Boost, and I'm still getting the same seg fault. 
Process 18915 launched: './SAAPFramework' (x86_64)
New Thread... parent: 1 child: 1 runtime: 479335736
Process 18915 stopped
- thread #1: tid = 0x1dacf, 0x0000000100013f56 SAAPFramework`ACC_ID::operator<(ACC_ID const&) const + 22, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x3)
  frame #0: 0x0000000100013f56 SAAPFramework`ACC_ID::operator<(ACC_ID const&) const + 22
  SAAPFramework`ACC_ID::operator<:
  ->  0x100013f56 <+22>: cmpl   (%rsi), %eax
  0x100013f58 <+24>: setb   %cl
  0x100013f5b <+27>: andb   $0x1, %cl
  0x100013f5e <+30>: movzbl %cl, %eax

**Comment by deknapp** [comment]
Do either of you understand what the debug output means here? This is the gdb output, when I have changed the strong typedef to typdef unsigned ACC_ID. 

Program received signal SIGSEGV, Segmentation fault.
0x0000000100014000 in std::__1::__tree_iterator<std::__1::__value_type<unsigned int, access_t const>, std::__1::__tree_node<std::__1::__value_type<unsigned int, access_t const>, void_>_, long> std::__1::__tree<std::__1::__value_type<unsigned int, access_t const>, std::__1::__map_value_compare<unsigned int, std::__1::__value_type<unsigned int, access_t const>, std::__1::less<unsigned int>, true>, std::__1::allocator<std::__1::__value_type<unsigned int, access_t const> > >::__lower_bound<unsigned int>(unsigned int const&, std::__1::__tree_node<std::__1::__value_type<unsigned int, access_t const>, void_>_, std::__1::__tree_node<std::__1::__value_type<unsigned int, access_t const>, void_>_) ()

**Comment by deknapp** [comment]
@wilhelma did you try running it on your Mac? did it work?

**Comment by wilhelma** [comment]
Should I try the nathan-debug branch? Why is there no CMakeLists.txt?

**Comment by deknapp** [comment]
No, use the developer branch.

On Tue, Jul 5, 2016 at 6:01 PM, wilhelma notifications@github.com wrote:

> Should I try the nathan-debug branch? Why is there no CMakeLists.txt?
> 
> > On 05 Jul 2016, at 17:39, deknapp notifications@github.com wrote:
> > 
> > @wilhelma https://github.com/wilhelma did you try running it on your
> > Mac? did it work?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub <
> > https://github.com/wilhelma/pcvInterpreter/issues/6#issuecomment-230515759>,
> > or mute the thread <
> > https://github.com/notifications/unsubscribe/AEDDw41S8lOnWSTrMYMcJ2en7fNAyv6hks5qSnqigaJpZM4JEUm2
> > .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/6#issuecomment-230522457,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwFRMlzubAzr-rJ-p_GMuffbjWbIuks5qSn_ggaJpZM4JEUm2
> .

## 

Nathaniel

**Comment by deknapp** [comment]
I have the code running on a virtual machine now, so I'll stop worrying
about the Mac issues for now.

On Tue, Jul 5, 2016 at 6:04 PM, Nathaniel Knapp nathaniel.knapp@gmail.com
wrote:

> No, use the developer branch.
> 
> On Tue, Jul 5, 2016 at 6:01 PM, wilhelma notifications@github.com wrote:
> 
> > Should I try the nathan-debug branch? Why is there no CMakeLists.txt?
> > 
> > > On 05 Jul 2016, at 17:39, deknapp notifications@github.com wrote:
> > > 
> > > @wilhelma https://github.com/wilhelma did you try running it on your
> > > Mac? did it work?
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub <
> > > https://github.com/wilhelma/pcvInterpreter/issues/6#issuecomment-230515759>,
> > > or mute the thread <
> > > https://github.com/notifications/unsubscribe/AEDDw41S8lOnWSTrMYMcJ2en7fNAyv6hks5qSnqigaJpZM4JEUm2
> > > .
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/wilhelma/pcvInterpreter/issues/6#issuecomment-230522457,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AHqFwFRMlzubAzr-rJ-p_GMuffbjWbIuks5qSn_ggaJpZM4JEUm2
> > .
> 
> ## 
> 
> Nathaniel

## 

Nathaniel

**Comment by wilhelma** [comment]
Fixed it... The bug was caused due to a unsafe usage of chained iterator accesses.

[see submit](https://github.com/wilhelma/pcvInterpreter/commit/bd08d2b45eb71d62d9a20fa65ab68a4fbd129e1f)
