### ISSUE TITLE
EXC_BAD_ACCESS with TRD_ID 

### ISSUE THREAD

**Issue by deknapp** [wilhelma/pcvInterpreter#7]
@pdigiglio 
I'm getting a EXC_BAD_ACCESS from the following line - line 167 in ParasiteTool.cpp, when I run scale_test.db with the compiled code for the nath-devel branch. 

ShadowThread::ThreadId newThreadID = _info->childThread->threadId;

Here is the lldb output: 
- thread #1: tid = 0x15ba0, 0x0000000100012f44 SAAPFramework`TRD_ID::TRD_ID(this=0x00007fff5fbfe460, t_=0xffffffffcc3895e9) + 20 at Types.h:32, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffffcc3895e9)
  frame #0: 0x0000000100012f44 SAAPFramework`TRD_ID::TRD_ID(this=0x00007fff5fbfe460, t_=0xffffffffcc3895e9) + 20 at Types.h:32
  29   BOOST_STRONG_TYPEDEF( ID, LOI_ID )
  30   BOOST_STRONG_TYPEDEF( ID, REF_ID )
  31   BOOST_STRONG_TYPEDEF( ID, SEG_ID )
  -> 32   BOOST_STRONG_TYPEDEF( ID, TRD_ID )
  33  
  34   // Access Types
  35   BOOST_STRONG_TYPEDEF( unsigned, POS )

Am I violating the strong typedef restrictions here?

**Comment by pdigiglio** [comment]
I've seen you changed your code already. Did it solve the problem?

**Comment by deknapp** [comment]
It solved a different problem

On Wed, Jul 6, 2016 at 4:13 PM, pdigiglio notifications@github.com wrote:

> I've seen you changed your code already. Did it solve the problem?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/7#issuecomment-230783917,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwK-49_0cZuSk1I3HBRHbXv4uOx_Qks5qS7f1gaJpZM4JGD0w
> .

## 

Nathaniel

**Comment by deknapp** [comment]
I committed my most recent changes to nath-devel.

**Comment by pdigiglio** [comment]
On my platform, `./SAAPFramework scale_test.db` throws a `std::out_of_range` exception. This means that the element you're trying to access with the following instruction:

``` cpp
std::shared_ptr<thread_frame_t> new_thread_frame = main_stack->thread_stack.at(main_stack->current_thread_index);
```

is not in there. I don't know if this might depend on the simulator. If you think so, I'll investigate; otherwise I'd assume it's not a bug of mine. Please let me know.

**Comment by deknapp** [comment]
Yes I know I found that already. Please see my most recent commit

On Wednesday, July 6, 2016, pdigiglio notifications@github.com wrote:

> On my platform, ./SAAPFramework scale_test.db throws a std::out_of_range
> exception. This means that the element you're trying to access with the
> following instruction:
> 
> std::shared_ptr<thread_frame_t> new_thread_frame = main_stack->thread_stack.at(main_stack->current_thread_index);
> 
> is not in there. I don't know if this might depend on the simulator. If
> you think so, I'll investigate; otherwise I'd assume it's not a bug of
> mine. Please let me know.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/wilhelma/pcvInterpreter/issues/7#issuecomment-230810277,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqFwHGPORp_nRp1OR5rq7ISFiqnaEAhks5qS8tUgaJpZM4JGD0w
> .

## 

Nathaniel

**Comment by pdigiglio** [comment]
I think I fixed it in [d417b1d](https://github.com/wilhelma/pcvInterpreter/commit/d417b1d15adec7a4e50c6bdae5658a4a29ea4a9e), please check it. Anyway, now you get again a `std::out_of_range` in `ParasiteTool::threadEnd()`.

**Comment by deknapp** [comment]
Thanks

**Comment by deknapp** [comment]
The problem is with the line 167 in ParasiteTool

On Wednesday, July 6, 2016, Nathaniel Knapp nathaniel.knapp@gmail.com
wrote:

> Yes I know I found that already. Please see my most recent commit
> 
> On Wednesday, July 6, 2016, pdigiglio <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > On my platform, ./SAAPFramework scale_test.db throws a std::out_of_range
> > exception. This means that the element you're trying to access with the
> > following instruction:
> > 
> > std::shared_ptr<thread_frame_t> new_thread_frame = main_stack->thread_stack.at(main_stack->current_thread_index);
> > 
> > is not in there. I don't know if this might depend on the simulator. If
> > you think so, I'll investigate; otherwise I'd assume it's not a bug of
> > mine. Please let me know.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/wilhelma/pcvInterpreter/issues/7#issuecomment-230810277,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AHqFwHGPORp_nRp1OR5rq7ISFiqnaEAhks5qS8tUgaJpZM4JGD0w
> > .
> 
> ## 
> 
> Nathaniel

## 

Nathaniel
